name: CI/CD Pipeline

on:
  push:
    branches:
      - new

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.14.0'

    - name: Install dependencies
      run: yarn install

    - name: Build the React app
      run: yarn build

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:latest .

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest

    - name: Create kube directory
      run: mkdir -p $HOME/.kube

    - name: Set up kubectl
      run: |
        echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 --decode > $HOME/.kube/config
        kubectl version --client

    - name: List files in the repository
      run: ls ./infrastructure/k8s

    - name: Apply Kubernetes Manifests
      run: |
        kubectl apply -f ./infrastructure/k8s/deployment.yaml
        kubectl apply -f ./infrastructure/k8s/service.yaml

    - name: Deploy to K3s
      run: |
        kubectl set image deployment/my-react-app my-react-app=${{ secrets.DOCKER_USERNAME }}/my-app:latest
        kubectl rollout status deployment/my-react-app
