name: CI/CD for React Project with Vite and Docker

on:
  push:
    branches:
      - new

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.14.0'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Create kube directory
        run: mkdir -p $HOME/.kube

      - name: Configure kubeconfig
        env:
          KUBE_CONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          cat <<EOF > $HOME/.kube/config
          apiVersion: v1
          clusters:
          - cluster:
              server: https://127.0.0.1:41001
            name: my-cluster
          contexts:
          - context:
              cluster: my-cluster
              user: github-actions
            name: my-context
          current-context: my-context
          kind: Config
          preferences: {}
          users:
          - name: github-actions
            user:
              token: ${KUBE_CONFIG}
          EOF

      - name: Update Kubernetes deployment
        run: kubectl --kubeconfig=$HOME/.kube/config set image deployment/ci-cd-test ci-cd-test=${{ secrets.DOCKER_USERNAME }}/my-app:latest
